# Generated by Django 4.1.7 on 2023-03-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-total_likes"], name="image_image_total_l_6c5288_idx"
            ),
        ),
    ]
